#!/usr/bin/env python3
"""Extract committed Hermes provider metadata without importing its runtime or user plugins.
Usage: python3 scripts/import-hermes-catalog.py /path/to/hermes-agent
The upstream checkout is read-only. Output is relative to this script's Keli checkout.
"""
import ast
import json
import pathlib
import subprocess
import sys

PIN = "93e2525a0b60c4e3f581ddf0bdf5ffe1bd977544"
upstream = sys.argv[1]

def git(*args):
    return subprocess.check_output(["git", "-C", upstream, *args], text=True)

rows = []
paths = git("ls-tree", "-r", "--name-only", PIN, "plugins/model-providers").splitlines()
for path in sorted(p for p in paths if p.endswith("/__init__.py")):
    tree = ast.parse(git("show", f"{PIN}:{path}"))
    constants = {}
    for node in tree.body:
        if isinstance(node, ast.Assign):
            try:
                value = ast.literal_eval(node.value)
                for target in node.targets:
                    if isinstance(target, ast.Name):
                        constants[target.id] = value
            except (ValueError, TypeError):
                pass
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        values = {}
        for key in node.keywords:
            try:
                values[key.arg] = ast.literal_eval(key.value)
            except (ValueError, TypeError):
                if isinstance(key.value, ast.Name) and key.value.id in constants:
                    values[key.arg] = constants[key.value.id]
        if not isinstance(values.get("name"), str) or not ("base_url" in values or "env_vars" in values):
            continue
        fields = ("name", "display_name", "aliases", "base_url", "env_vars", "auth_type", "api_mode", "default_aux_model", "fallback_models")
        rows.append({k: values[k] for k in fields if k in values})

# Definitions generated by upstream helper functions or living in the CLI catalog.
extras = [
    ("openai-api", "https://api.openai.com/v1", ["OPENAI_API_KEY"], "gpt-5.4-mini", "codex_responses"),
    ("lmstudio", "http://localhost:1234/v1", [], None, "chat_completions"),
    ("kimi-coding", "https://api.moonshot.ai/v1", ["KIMI_API_KEY", "KIMI_CODING_API_KEY"], "kimi-k2-turbo-preview", "chat_completions"),
    ("kimi-coding-cn", "https://api.moonshot.cn/v1", ["KIMI_CN_API_KEY"], "kimi-k2-turbo-preview", "chat_completions"),
    ("tencent-tokenhub", "https://tokenhub.tencentmaas.com/v1", ["TOKENHUB_API_KEY", "TOKENHUB_BASE_URL"], None, "chat_completions"),
    ("tencent-tokenplan", "https://api.lkeap.cloud.tencent.com/plan/anthropic", ["TOKENPLAN_API_KEY", "TOKENPLAN_BASE_URL"], None, "anthropic_messages"),
    ("xai-oauth", "https://api.x.ai/v1", [], "grok-4", "codex_responses"),
]
for name, url, env, model, mode in extras:
    rows.append(dict(name=name, base_url=url, env_vars=env, default_aux_model=model, api_mode=mode))
for row in rows:
    if row["name"] == "meta-ai":
        row["base_url"] = "https://api.meta.ai/v1"
    if row["name"] == "router":
        row["base_url"] = "https://api.router.com/v1"
    if row["name"] == "xai":
        row.update(name="grok", aliases=["xai", "x-ai", "x.ai"], default_aux_model="grok-4")
rows.append(dict(name="moa", display_name="Mixture of Agents", auth_type="virtual"))
target = pathlib.Path(__file__).resolve().parent.parent / "src/integrations/hermes-catalog.json"
target.write_text(json.dumps(rows, indent=2) + "\n")
print(f"Wrote {len(rows)} inference snapshot rows from Hermes {PIN}")
print("Run bun run scripts/import-provider-manifest.ts to refresh the public manifest.")
